---
- hosts: localhost

  tasks:
    - name: Get all groups from inventory
      set_fact:
        groupnames: "{{ groups.keys() | list }}"
      
    - name: Set date variable
      set_fact:
        dategroups: "{{ item | regex_search('^date_') }}"
        timegroups: "{{ item | regex_search('^time') }}" 
        appgroups: "{{ item | regex_search('^type') }}"
      with_items: "{{ groupnames }}"
      
      
    - name: Prep group scheduling
      debug:
        msg: "GroupNames : {{ groupnames }}; DateGroups: {{ dategroups }}; TimeGroups : {{ timegroups }}; AppGroups: {{ appgroups }}"

