---
- hosts: localhost

  tasks:
    - name: Get all groups from inventory
      set_fact:
        groupnames: "{{ groups.keys() | list }}"
      
    - name: Set date variable
      set_fact:
        dategroups: "{{ item }}"
      when: "{{ item | regex_search('^date_') }}"
      with_items: "{{ groupnames }}"

    - name: Set time variable
      set_fact:  
        timegroups: "{{ item }}"
      when: "{{ item | regex_search('^time') }}"
      with_items: "{{ groupnames }}"

    - name: Set app variable facts
      set_fact:  
        appgroups: "{{ item }}"
      when: "{{ item | regex_search('^type') }}"
      with_items: "{{ groupnames }}"
      
      
    - name: Prep group scheduling
      debug:
        msg: "GroupNames : {{ groupnames }}; DateGroups: {{ dategroups }}; TimeGroups : {{ timegroups }}; AppGroups: {{ appgroups }}"

