---
- hosts: all
  tasks:
    - name: Refresh package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Update all packages
      apt:
        name: '*'
        state: latest
