---
- hosts: localhost
  collections:
    - awx.awx
  
  vars:
    - date: '2022-03-19 22:19:00'
    - timezome: 'America/Winnipeg'

  tasks:
    - name: set Date time
      set_fact:
        datetime: "{{ date |  regex_replace('-') | regex_replace(' ','T') |  regex_replace(':') }}"
        # | regex_replace('^(.*)$','\\1Z')
        # time: "{{ date |  to_datetime('%H%M%S') }}"
      
    - name : show date time and rrule
      debug:
        #var: datetime
        msg: "DTSTART;TZID={{ timezome }}:{{ datetime }} RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"

    - name: Build schedule
      schedule:
        name: "Patching_{{ item }}"
        state: present
        unified_job_template: "Run Patch"
        inventory: AWS-Inventory
        limit: "_{{ item }}"
        organization: "Evenproton"
        rrule: |
          DTSTART;TZID={{ timezome }}:{{ datetime }} 
          RRULE:FREQ=DAILY;COUNT=1;INTERVAL=1
      with_items:
        - A
        - B


