---
- hosts: localhost
  collections:
    - awx.awx
  
  vars:
    - date: '2022-03-16 16:00:00'

  tasks:
    - name: Generate schedule
      tower_schedule_rrule:
        _terms: none
        start_date: "{{ date }}"
      register: schduleddate

    - name: Build schedule
      schedule:
        name: Patching
        state: present
        unified_job_template: "Run Patch"
        inventory: "_{{ item }}"
        organization: "Evenproton"
        rrule: "{{ scheduleddate.stdout }}"
      with_items:
        - A
        - B
        - C
